### ISSUE TITLE
Bug of ./src/screens/DisplayList/DisplayList.js

### ISSUE THREAD

**Issue by vadim9999** [GroceriStar/groceristar-fetch#109]
When I install module groceristar-fetch version 1.1.26
I get error:
```
./src/screens/DisplayList/DisplayList.js
Module not found: Can't resolve '@groceristar/groceristar-fetch/groceristar' in 
'..\react-shopping-list-template\src\screens\DisplayList'
```

**Comment by GuiFSs** [comment]
so, now the way we import modules from groceristar-fetch changed, the correct way would be e.g: `const { groceristar } = require('@groceristar/groceristar-fetch');
console.log(groceristar.getAllDepartments());` or `import { groceristar, mealCalendar } from '@groceristar/groceristar-fetch';`

**Comment by atherdon** [comment]
@GuiFSs did you open a PR with this changes?

**Comment by atherdon** [comment]
@vadim9999 can you publish latest Guilherme changes and check if this is solved our issue at React project?

**Comment by atherdon** [comment]
we also should have an updated version of our Readme or documentation...

**Comment by vadim9999** [comment]
yes it's solved problem

**Comment by atherdon** [comment]
did you publish a new version of plugin to npm? should i run updates for
our other projects?

**Comment by vadim9999** [comment]
We have a probleb in react-shopping-list-template. I need change imports from import gf from '@groceristar/groceristar-fetch/groceristar';
to this 
const { groceristar } = require('@groceristar/groceristar-fetch'); console.log(groceristar.getAllDepartments());

**Comment by vadim9999** [comment]
It needs to change in all projects

**Comment by atherdon** [comment]
ok, can @GuiFSs help you with this task? will you be able to get list of all projects, that require this changes?

**Comment by atherdon** [comment]
and lets create a separated task for discussing this work. because this place was for bug, and we should close it

**Comment by atherdon** [comment]
i'll do it myself.

**Comment by atherdon** [comment]
> Yes. I have done publish npm. After update to v1.1.27 We have a problem in react-shopping-list-template. I need change imports from
> 
> ```
> import gf from '@groceristar/groceristar-fetch/groceristar';
> ```
> to this
> 
> ```
> const { groceristar } = require('@groceristar/groceristar-fetch'); 
> ```
