### ISSUE TITLE
Need to add a method called get grocery list by department. 

### ISSUE THREAD

**Issue by kaiz123** [GroceriStar/groceristar-fetch#110]
This will be used in react-shopping-list-template in order to display grocery list when navigate to route with department_id parameter.

**Comment by atherdon** [comment]
Give us more details @kaiz123 what should be done and what should be returned.

**Comment by atherdon** [comment]
@kaiz123 will you be able to help us? we starting to work on it, but details are welcomed

**Comment by kaiz123** [comment]
Im not sure about what would a grocery list associated with a specific department contain.

**Comment by atherdon** [comment]
hmm, so how we should make it in this case?

grocery usually contain departments and ingredients ;)

**Comment by atherdon** [comment]
@kaiz123 done by this PR: https://github.com/GroceriStar/groceristar-fetch/pull/126
soon will update package at our project

**Comment by kaiz123** [comment]
Sure. Looks good.

**Comment by atherdon** [comment]
Will close it when 
1) we publish our changes at npm, 
2) documentation website will be published,
3) I'll update our react projects 
4) Kaiz will confirm that current method is ok and can be used
5) done

**Comment by atherdon** [comment]
@kaiz123 we published a method that you've requested. i also update package at our project. please take a look: https://github.com/GroceriStar/groceristar-fetch/blob/docu/docs/Groceristar.md#get-an-array-of-grocery-lists-based-on-department

**Comment by kaiz123** [comment]
Looks good.
