### ISSUE TITLE
add id field to departments.json

### ISSUE THREAD

**Issue by kaiz123** [GroceriStar/groceristar-fetch#111]
- will be used in react-shopping-list-template for routing with department id param

**Comment by atherdon** [comment]
@kaiz123 i think you can check this methods and create something similar to this:
https://github.com/GroceriStar/groceristar-fetch/blob/master/projects/GroceriStar/groceristar.js#L100-L122
Tell me if i can assign this task to you

**Comment by atherdon** [comment]
we decided to not have this id numbers at json. this is why we using this uuid thing. please use it for our current work. Later we'll have a real base and this issue will be fixed.
If you want- you can create a separated method, so id will be generated for `id` field, not for key...
I think you can solve this task by yourself

**Comment by kaiz123** [comment]
If we have decided not to keep id inside the json then I think in the
frontend we can just have the department name as the route parameter as
that is unique. Generating the id in any other way except keeping it in the
json won't work.

**Comment by kaiz123** [comment]
Okay, will keep this open until there's a suitable solution found

**Comment by atherdon** [comment]
if we have a one place - where we get all ids generated - i think this cannot be an issue for this moment. i agree that this is not a good turn around - but while we rebuildin our server - this is the only one

**Comment by atherdon** [comment]
i think it's solved, because we're generate an id in our methods. it works for now.
