### ISSUE TITLE
[Groceristar project][Departments][Vadim]

### ISSUE THREAD

**Issue by atherdon** [GroceriStar/groceristar-fetch#12]
- [x] Department names -> Please add this section to grocery.json
structure will be like this: `grocery[0][departments][0]` and it will return a department name

Create a few methods, using library lodash/underscore that will return this data
- [x] display all departments from grocery.json
- [x] display all ingredients at one department

**Comment by vadim9999** [comment]
@atherdon There is no file grocery.json. Where can I find it? Or do you mean groceryData.json?

**Comment by atherdon** [comment]
yes, and please replace that name :0 and other files that you moved :)


On 11-Jul-2018 at 08:31 AM, Vadim wrote:


@atherdon <https://github.com/atherdon> There is no file grocery.json.
Where can I find it? Or do you mean groceryData.json?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/GroceriStar/groceristar-fetch/issues/12#issuecomment-404088720>,
or mute the thread

**Comment by atherdon** [comment]
and it should work :)


On 11-Jul-2018 at 08:31 AM, Vadim wrote:


@atherdon <https://github.com/atherdon> There is no file grocery.json.
Where can I find it? Or do you mean groceryData.json?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/GroceriStar/groceristar-fetch/issues/12#issuecomment-404088720>,
or mute the thread

**Comment by atherdon** [comment]
ok, i tried to create a voice explanation video how to create a pull request, but my mic was not off - so you'll see only my screen, hope it'll help you: https://www.useloom.com/share/03fe35fc61f54d8db4a884657c6c2dfa

**Comment by atherdon** [comment]
@vadim9999 can you specify a code line, where did you implement this methods: _display all departments from grocery.json_, _display all ingredients at one department_

**Comment by vadim9999** [comment]
@atherdon https://github.com/GroceriStar/groceristar-fetch/blob/0c78998c4ce724c374b2e63ec4ee72aa5c196d2c/index.js#L142

**Comment by atherdon** [comment]
Please add this methods to Readme file and close this issue after that
