### ISSUE TITLE
update documentation for methods from PR 126

### ISSUE THREAD

**Issue by atherdon** [GroceriStar/groceristar-fetch#127]
Add details/explanation how the method works with an example to `docu` branch.
this file: https://github.com/GroceriStar/groceristar-fetch/blob/docu/docs/Groceristar.md

After merging this changes - buzz Vadim, so he'll publish an updated version of website at hosting

**Comment by Avuidrauxs** [comment]
Okay I'm on it

**Comment by atherdon** [comment]
please follow this link: https://github.com/GroceriStar/groceristar-fetch/invitations
