### ISSUE TITLE
[Groceristar project][Add other grocerylists][Vadim]

### ISSUE THREAD

**Issue by atherdon** [GroceriStar/groceristar-fetch#15]
right now, in our grocery.json we have only one instance of grocery list.
we need to add other 6-7 GL that we have into our package.
But please do it in a smarter way: we should avoid duplicates: our json should have only clean data.
For example: Ultimate grocery have a department 'Dairy', and one of other grocery lists have a same department - so we don't need to create another row at departments.json - because we have it before.

for checking duplicates please create some js code that will run through json files and see if we have duplicates or not.

First of all - you should create other files in folders `Departments` & `Ingredients`, that will be related to a new grocery lists.

You can find data, related to this grocery lists here: 
https://github.com/GroceriStar/static-data/tree/master/dist/data/gl

- [x] dont forget to move readme, related to this GL
- [x] delete that files from static-data repo when you'll complete this task

**Comment by vadim9999** [comment]
@atherdon Sorry, I can't understand what to do.  
clean-fatirig-grocery-list.js
gl-essentials.js
healthy-vegetarian-grocery-list.js
keto-diet-food-list.js
low-carb-food-list.js
rebel-dietitian.js
we have this files. In each file are title - name of department and ingredients of this department.

**Comment by atherdon** [comment]
please compare this files, with structure, that you imported to this
package previous times.
is it similar? no, but it should be.

so, let's start first one:
you need to move it into this repo.
then in some file include that js file.
also you'll need to include files like Ingredients/ingredients.json or
Departments/departments.json. let's assume that you'll use underscore.
so, you do map function - extract each ingredient from clean-fatirig file
and search it in Ingredients/ingredients.json if ingredient from
clean-fatirig is unique -> you should store it in new array. later, all
data from that new array you'll add to ingredients.json

So, right now at Groceristar project - we have only 1 Grocery List. But we
want to extend that functionality, so we need to prepare data for import to
database.
and your goal is compare data, that actually was imported, with data from
new GroceryLists. and add a new data.

tell me if this is still not clear, i'm ok to explain more


On 11-Jul-2018 at 12:28 PM, Vadim wrote:


@atherdon <https://github.com/atherdon> Sorry, I can't understand what to
do.
clean-fatirig-grocery-list.js
gl-essentials.js
healthy-vegetarian-grocery-list.js
keto-diet-food-list.js
low-carb-food-list.js
rebel-dietitian.js
we have this files. In each file are title - name of department and
ingredients of this department.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/GroceriStar/groceristar-fetch/issues/15#issuecomment-404151337>,
or mute the thread

**Comment by atherdon** [comment]
I can create a simple video that will explain exact steps that we need @vadim9999

**Comment by vadim9999** [comment]
@atherdon In this project are two folders and their files 
Ingredient -> ingredients.json
                 ->ingredients2.json
and
 Ingredients -> ingredients.json
What to do?

**Comment by atherdon** [comment]
awhat file did you created? use it


On 12-Jul-2018 at 11:03 AM, Vadim wrote:


@atherdon <https://github.com/atherdon> In this project are two folders and
their files
Ingredient -> ingredients.json
->ingredients2.json
and
Ingredients -> ingredients.json
What to do?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/GroceriStar/groceristar-fetch/issues/15#issuecomment-404475331>,
or mute the thread

**Comment by atherdon** [comment]
@vadim9999 don't forget to remove grocery lists from old repository
