### ISSUE TITLE
ingredient list 

### ISSUE THREAD

**Issue by atherdon** [GroceriStar/groceristar-fetch#176]
based on https://github.com/GroceriStar/react-shopping-list-template/pull/169

In order to have a cool web based grocery list we should have nice UI that help us to manage ingredients.
This is why we've created a big number of small components.
on your last PR i find that you're passing a small amount of data into that lists.
This is what you've send
```
        <List3Links data={
          [{name: "all",
            status: "all"},
          {name:"active",
            status: "active",},
          {name: "purchased",
          status: "purchased"}]}/>
```

List like on this example should be ready to receive more advanced array. 
It is an array of ingredients, that grouped by department.
Btw, can you tell me where we're using this method - `getAllIngredientsList`?

If we didn't use this method before, you can adjust it. But we should know that this is didnt broke the structure in other projects or tests. So in order to our react component more live-data you can extend this method
instead of return
```

    key: uuidv1(),
    name: item.name,
    isChecked: false


```

add
```
    key: uuidv1(),
    name: item.name,
    isChecked: false,
    departmentID: ...,
    order: ... //order is a number that show order of ingredient in list. so ingredient with order 0 will appear on top of the list, so it should be also sorted(for example if we receive data, that didn't sorted well, aka [3,5,7, 1, 6, 2, 0]).


```
isChecked equal to your 'purchased' status at React.

**plus** we also need to have 3 basic links, but this is should be discussed later. Make a note and buzz me at react project.

**Comment by vadim9999** [comment]
I can't understand about where should be three links? why it's needs? What they should do?

**Comment by atherdon** [comment]
i'll explain links whne we'll complete main part of this task.

**Comment by atherdon** [comment]
quick answer: check images below
![123](https://raw.githubusercontent.com/GroceriStar/creative/master/prev.%20design.screens/Shopping%20List%20%2059f1695cd534650012ae0ee7.png)
![123](https://raw.githubusercontent.com/GroceriStar/creative/master/prev.%20design.screens/Shopping%20List%20%205a6fb00ef3909e0012274dab%20(1).png)
![123](https://raw.githubusercontent.com/GroceriStar/creative/master/prev.%20design.screens/Shopping%20List%20%205a6fb00ef3909e0012274dab.png)

**Comment by vadim9999** [comment]
In PR https://github.com/GroceriStar/react-shopping-list-template/pull/176
