### ISSUE TITLE
upgrade importing files process

### ISSUE THREAD

**Issue by atherdon** [GroceriStar/groceristar-fetch#177]
Each project-related file has a list of required files.
We should move them away, into a separated file.

Before: 
```
const mealCalendar = require('../../data/MealCalendar/mealcalendar.json');
```

after
```
const { mealCalendar }  = require('./files');
```
Use the same approach at *.test files too.
You can see a completed version at `mealCalendar`
In order to test if it works fine, run `npm run test`

**Comment by kraftaa** [comment]
Arthur,
Am I correct that in Project folder in all files I have to change from (eg ```ChickenKyiv```)

```
const ingredients3 = require('../../data/Ingredients/ingredients3.json');
// const ingredients  = require('../../data/Ingredients/ingredients.json');

const menus        = require('../../data/Menu/menu.json');
const recipes      = require('../../data/Recipe4/recipe.json');
const nutritions1  = require('../../data/Nutrition/nutritions1.json');
const nutritions2  = require('../../data/Nutrition/nutritions2.json');

```

into

```
const {ingredients3} = require('./files');

const {menus}        = require('./files');
const recipes      = require('./files');
const nutritions1  = require('./files');
const nutritions2  = require('./files');
```
I see we have `files.js` in `mealCalendar` with all paths. Do we need such files in other Project folders ?

thank you!

**Comment by atherdon** [comment]
yes, you right, or you can use a short version
```
const { recipes, menus } = require('./files');
```

yes, we need to have the same approach at other projects too. btw, as you also can see - that `staticFiles.test.js` testing if files have data. I think we need to rename it into `files.test.js`. 
These changes later will help us to split this plugin into two pieces.

**Comment by atherdon** [comment]
side note - please use a pull request logic. Right now you have access to merge your changes into the main repository, but it requires double checking. For example, right now some of our tests crash after your commits and we weren't aware of it. with PR we have a build setting, that runs all tests automatically.

**Comment by atherdon** [comment]
you can see it here: https://github.com/GroceriStar/groceristar-fetch/commits/master

**Comment by atherdon** [comment]
side note: you can check if json file is valid here: https://jsonlint.com/

**Comment by kraftaa** [comment]
Hi Arthur,
thank you for the detailed instructions. 
I've updated all files and created new `files.js` in each folder.
All updated files are in my fork now.
I've run `npm run test` but it failed test with
```const dayjs        = require('dayjs');```
it couldn't find module `dayjs` from `chickenKyiv.js`

I've checked files in `jsonlint.com` but it crashes on
`const _ = require('lodash');`
`Error: Parse error on line 1:
const _ = require('l
^
Expecting 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '[', got 'undefined'
`

thank you!

**Comment by atherdon** [comment]
i assume this problem:
you pull our last changes, but didn't re-run an installation process. so your `node_modules` has old cashed plugins, instead of new, that we installed few days ago.

so run yarn install - it will clean local modules cache and re install each plugin. i think it'll help.
buzz me if issue still appear.

Btw, jsonlint is still not finished work. I mean it works, but it doesn't include into our development process automatically(like tests for example). i assume here a same issue - you just don't have this package locally. re-install should help too

**Comment by atherdon** [comment]
Btw, jsonlint only for json files. it wouldn't work with JS code

**Comment by atherdon** [comment]
@kraftaa I saw that you've started to work on this task on your repo, but didn't push changes here.
did you finish it or it's still pending? The reason why i'm asking - i'm dramatically changing the logic right now, so we may have some conflicts between our versions.

**Comment by atherdon** [comment]
I think this task completed. tell me if I'm wrong
