### ISSUE TITLE
"groceristar" big object

### ISSUE THREAD

**Issue by atherdon** [GroceriStar/groceristar-fetch#185]
main task: #60 

I think it's a good time to work on this task.
The first version we will battle test at showcase - we have an issue there: https://github.com/GroceriStar/showcase/issues/197

## GL
structure of our collection should be:
```
[
{ 
  key: uuid(),  
  name: 'gl name',
  dep: [
    {
      id: uuid(),
       ing: [
        {
          id: uuid()
        }
      ]
    }
  ]
}
]
```
But be ready for example to create a different type of structure:
```
[
{ 
  key: uuid(),  
  name: 'gl name',
  ing: [
    {
      id: uuid(),
       dep: 
        {
          id: uuid()
        }     
    }
  ]
}
]
```

---

Today I run our REST api server and print ultimate GL that we have. i think it'll give some details about what we need to have:
https://github.com/GroceriStar/groceristar-fetch/blob/master/data/Grocery/example/ultimate-gl-from-loopback-server-example.json

---

We have a lot of stuff going on at our groceristar file.
I decide to move away basic methods, that will grab data, related to json response from our groceristar API server. you can see it at folder **GS-Loopback**

--

I also moved methods from groceristar into loopback that we'll need.
 i comment them, because i didn't finish it. We need to have logic from this mehods, but ported into our second file. So for example, instead of getting all departments and add them uuid - we just need to grab departments with their ids and return that array.

we need to update these methods, export and test at play.js - call this file via `yarn run play:l`

**Comment by atherdon** [comment]
i forgot to tell you, that GS swagger works too ;( 
check this link: http://groceristar.herokuapp.com/explorer/

**Comment by vadim9999** [comment]
```
groceristar.getGroceryByNameWithDepAndIngKey("Ultimate Grocery List")
```
Result
```
{ name: 'Ultimate Grocery List',
  groceryId: '2ac2efd0-2731-11e9-8e23-c107aeb8a6c6',
  messages: {},
  departments:
   [ { id: '2a0c22f0-2731-11e9-8e23-c107aeb8a6c6',
       name: 'Fresh vegetables',
       type: 'food',
       ingredients:[ [ '2a0aea70-2731-11e9-8e23-c107aeb8a6c6',
    'Asparagus',
    '/del/ing/2a0aea70-2731-11e9-8e23-c107aeb8a6c6/2ac2efd0-2731-11e9-8e23-c107aeb8a6c6' ],
  [ '2a0b1180-2731-11e9-8e23-c107aeb8a6c6',
    'Broccoli',
    '/del/ing/2a0b1180-2731-11e9-8e23-c107aeb8a6c6/2ac2efd0-2731-11e9-8e23-c107aeb8a6c6' ],
  [ '2a0b1181-2731-11e9-8e23-c107aeb8a6c6',
    'Carrots',
    '/del/ing/2a0b1181-2731-11e9-8e23-c107aeb8a6c6/2ac2efd0-2731-11e9-8e23-c107aeb8a6c6' ],
  [ '2a0b1182-2731-11e9-8e23-c107aeb8a6c6',
    'Cauliflower',
    '/del/ing/2a0b1182-2731-11e9-8e23-c107aeb8a6c6/2ac2efd0-2731-11e9-8e23-c107aeb8a6c6' ],]
 },
     { id: '2a12d9bf-2731-11e9-8e23-c107aeb8a6c6',
       name: 'Condiments / Sauces',
       type: 'food',
       ingredients: [ [ '0b097cd0-2732-11e9-a8db-1b8cee2c983f',
    'BBQ sauce',
    '/del/ing/0b097cd0-2732-11e9-a8db-1b8cee2c983f/2ac2efd0-2731-11e9-8e23-c107aeb8a6c6' ],
  [ '0b097cd1-2732-11e9-a8db-1b8cee2c983f',
    'Gravy',
    '/del/ing/0b097cd1-2732-11e9-a8db-1b8cee2c983f/2ac2efd0-2731-11e9-8e23-c107aeb8a6c6' ],
  [ '0b097cd2-2732-11e9-a8db-1b8cee2c983f',
    'Honey',
    '/del/ing/0b097cd2-2732-11e9-a8db-1b8cee2c983f/2ac2efd0-2731-11e9-8e23-c107aeb8a6c6' ],]
},
}
```

**Comment by atherdon** [comment]
hmm, so we have it, right?

What about displaying all grocery lists at one array?

**Comment by vadim9999** [comment]
some departments from grocery doesn't exist in departments.json 
Maybe it's someone helps
```
Undefined  PROTEIN
Undefined  STARCH
Undefined  HEALTHY FATS
Undefined  VEGGIES
Undefined  BEVERAGES
Undefined  FRUITS
Undefined  OILS AND SEEDS
Undefined  SEASONINGS
Undefined  MEAT/PROTEIN
Undefined  DAIRY
Undefined  FRUITS
Undefined  SNACKS
Undefined  VEGETABLES
Undefined  BAKING
Undefined  GRIS
Undefined  Bulk Foods
Undefined  Canned Goods/Pantry
Undefined  Herbs/Spices
Undefined  Frozen Foods
Undefined  Oils, Vinegars, and Condiments
Undefined  FATS
Undefined  KETO SNACKS
Undefined  PROTEIN
Undefined  VEGGIES
Undefined  CONDIMENTS
Undefined  DRINKS
Undefined  FLOUR
Undefined  FRUITS
Undefined  Meat/Fish Poultry
Undefined  Cheese/Dairy
Undefined  Cheses In 1 Ounce Portions
Undefined  Fats and Dressings
Undefined  Zero Carb Drinks
Undefined  Nuts/Seeds
Undefined  Soy Vegan Protein
Undefined  Herbs/Spices
Undefined  Zero Carb Alcoholic Drinks
Undefined  staples
Undefined  tinnedFood
Undefined  vegetables
Undefined  fruits
Undefined  meat
Undefined  condiments
Undefined  dairy
Undefined  spreads
Undefined  cookingBaking
Undefined  drinks
Undefined  pastry
Undefined  sweets
Undefined  grains and flours
Undefined  single ingredient food
Undefined  produce
Undefined  vegetarian protein source
Undefined  dairy like stuff
Undefined  dry stuff
Undefined  other
Undefined  breads-and-grains
Undefined  dairy-and-eggs
Undefined  meats
Undefined  fresh produce
Undefined  frozen items
Undefined  pantry staples
Undefined  other
Undefined  other
Undefined  carbs
Undefined  ProteinSources
Undefined  DairyMilk
Undefined  produce
Undefined  CondimentsMiscellaneous
Undefined  FrozenFoods
Undefined  produce
Undefined  herbs
Undefined  meat, fish and soy proteins
Undefined  grocery items
Undefined  oils, vinegar and condiments
Undefined  spices
Undefined  nuts and seeds
Undefined  other
Undefined  fruits
Undefined  vegetables
Undefined  grains
Undefined  protein
Undefined  dairy
Undefined  pantry
Undefined  other
Undefined  other
Undefined  other
Undefined  pantry ingredients
Undefined  other
Undefined  other
Undefined  beans
Undefined  rice
Undefined  pasta
Undefined  other grains
Undefined  canned tomatoes
Undefined  canned vegetables
Undefined  canned and dried fruits
Undefined  sauces
Undefined  soups
Undefined  meats
Undefined  other
Undefined  vinegars
Undefined  oils
Undefined  reduced fat cheeses
Undefined  dairy
Undefined  breads
Undefined  fish
Undefined  other
Undefined  other
Undefined  shopping list
Undefined  each week buy
Undefined  detox vegetable broth ingredients
Undefined  carbs
Undefined  ProteinSources
Undefined  DairyMilk
Undefined  produce
Undefined  CondimentsMiscellaneous
Undefined  FrozenFoods

```

**Comment by vadim9999** [comment]
In PR https://github.com/GroceriStar/groceristar-fetch/pull/196
this method returns array of objects like in example ultimate-gl-from-loopback-server-example
groceristar.getGroceriesWithDepIngKey()

**Comment by atherdon** [comment]
> some departments from grocery doesn't exist in departments.json
> Maybe it's someone helps
> 
> ```
> Undefined  PROTEIN
> Undefined  STARCH
> Undefined  HEALTHY FATS
> Undefined  VEGGIES
> Undefined  BEVERAGES
> Undefined  FRUITS
> Undefined  OILS AND SEEDS
> Undefined  SEASONINGS
> Undefined  MEAT/PROTEIN
> Undefined  DAIRY
> Undefined  FRUITS
> Undefined  SNACKS
> Undefined  VEGETABLES
> Undefined  BAKING
> Undefined  GRIS
> ```
we need to post this into some separated issue and mention what you've found at our "discussion task"

**Comment by atherdon** [comment]
@vadim9999 
1) create a separated issue with content from this comment https://github.com/GroceriStar/groceristar-fetch/issues/185#issuecomment-460002543
2) mention that issue at "Discussion task"
3) create a method, that will pack all groceries. Because right now i think we cannot get an array with all grocery lists, by calling them via `getGroceriesWithDepIngKey`

**Comment by vadim9999** [comment]
@atherdon it's returns all grocery lists in one array maybe instead of map I shoud use forEach

**Comment by atherdon** [comment]
hmm, i didn't check how the method works, and cannot confirm are you right or not @vadim9999 
But i'm aware that in showcase we have an issue, when latest added grocery lists didn't have correct ingredients inside. https://github.com/GroceriStar/showcase/issues/197 Please review and tell me what do you think.
I also think that showcase can be a good platform for testing how this method are really working

**Comment by atherdon** [comment]
Maybe you can make my life easier, by creating a few sets of tests, that will test this method and will help me to believe that everything works perfect. it'll really helps and save my time(as usually, i don't have a lot of time for a proper review)

**Comment by vadim9999** [comment]
Ok. I Will create a task in trello

**Comment by atherdon** [comment]
perfect idea. i think you realized why i like to keep everything organized
;)
I'll add some details to that task too.

**Comment by atherdon** [comment]
by setting you mean stuff like `styles={color:blabla}`, right? from method getGroceryShowcase 

if i got you right - let's focus on tests, related to the current method - so we or I will 100% sure that data that we combining - are good and works fine at any case....

**Comment by Avuidrauxs** [comment]
> I think we can use this method at graphQL server as well
> 
> @aanchirinah can you add one method to graphql-server selector, that will incorporate info from [#185 (comment)](https://github.com/GroceriStar/groceristar-fetch/issues/185#issuecomment-460000964)
> So our graphql backend developer will be able to use it.
> 
> **Note** I should publish a newest version of fetch plugin into npm, in order to export last changes, that Vadim did. I'll buzz when i did it.
> 
> **UPD** I published the 60th version of this package. RIght now it has latest Vadim`s changes. Audax, you can move forward with this task

@atherdon , Review this [PR](https://github.com/GroceriStar/graphql-server/pull/54)
