### ISSUE TITLE
update methods that return random elements

### ISSUE THREAD

**Issue by atherdon** [GroceriStar/groceristar-fetch#189]
Proposal: use lodash methods for returning random elements
and replace few of our Math.random methods with _.random
```
var randomArray = [
   '#cc0000','#00cc00', '#0000cc'
];

// use _.sample
var randomElement = _.sample(randomArray);

// manually use _.random
var randomElement = randomArray[_.random(randomArray.length-1)];
```
https://lodash.com/docs/4.17.11#sampleSize

#170

**Comment by atherdon** [comment]
@wahaj-47 if i understand you correctly - we have one method left, that require your changes, right?

**Comment by wahaj-47** [comment]
I don't think so, which method is left ?
Can't seem to find it.

**Comment by atherdon** [comment]
I mean this is your message
> In the method getFiveRandomIngredients() why are we fetching all the recipes and then picking ingredients of random 5 recipes. Instead we can use the getRandomRecipe() method to return n random recipe and then just pick their ingredients.

did you commit that changes too? @wahaj-47

**Comment by wahaj-47** [comment]
Yeah

**Comment by atherdon** [comment]
got it, then closing this task. you can move to a next one
