### ISSUE TITLE
i published an update (sample from real server)

### ISSUE THREAD

**Issue by atherdon** [GroceriStar/groceristar-fetch#191]
I grab static data from our groceristar API server.
exported them to this plugin and made them accessible outside.
at this task you need to connect methods, that return this data at our few projects.
all this methods stored at loopback folder: https://github.com/GroceriStar/groceristar-fetch/tree/master/projects/GS-Loopback
all methods should be exported at selector files:
- [x] showcase, https://github.com/GroceriStar/showcase, https://github.com/GroceriStar/showcase/blob/master/src/selectors/selector.js

- [x] shoplist template, https://github.com/GroceriStar/react-shopping-list-template, https://github.com/GroceriStar/react-shopping-list-template/blob/master/src/selectors/selector.js

- [x] fake-api, https://github.com/GroceriStar/fake-api/blob/master/app/selectors/selector.js
- [x] graphQL-server, https://github.com/GroceriStar/graphql-server/blob/master/src/data/selector.js

**Comment by atherdon** [comment]
@aanchirinah do you want to grab this quick task?

**Comment by Avuidrauxs** [comment]
@atherdon , Yes I would love to

**Comment by atherdon** [comment]
awesome. it's yours. with this task we'll train your 'vision' between projects

**Comment by atherdon** [comment]
no. At `loopback` folder we have 3 methods right now.
I want to be able to call these methods at projects, that i list below

**Comment by atherdon** [comment]
so at fetch plugin we `exported` main loopback object and 3 methods. and
your task will be `import` this object with methods

**Comment by Avuidrauxs** [comment]
@atherdon , So you want me to rather import the loopback methods into the other projects using the selector pattern?

**Comment by atherdon** [comment]
yep.
Show me the code at PRs and i'll tell you if you wrong :)

**Comment by atherdon** [comment]
@Avuidrauxs yes, this is what we need! submit as PRs and i'll approve it

**Comment by Avuidrauxs** [comment]
@atherdon , when I pulled recent changes from `Fetch` I noticed we have failed tests

**Comment by Avuidrauxs** [comment]
@atherdon , Here is the  [PR](https://github.com/GroceriStar/showcase/pull/202) for Showcase

**Comment by atherdon** [comment]
Plus you can add some test at index.test.js in order to completely connect loopback-related methods.
I'm publishing right now your fix at npm, so we will be able to receive this methods at our react projects.

**Comment by atherdon** [comment]
i updated fetch package at showcase, fake-api,  grapql, shoplist - you can continue this task

**Comment by Avuidrauxs** [comment]
@atherdon 
Shoplist template [PR](https://github.com/GroceriStar/react-shopping-list-template/pull/183)

Fake-API  [PR](https://github.com/GroceriStar/fake-api/pull/11)

**Comment by atherdon** [comment]
buzz me when you'll update selectors at graphQL server - just want to close this task

**Comment by atherdon** [comment]
ok, it's done, closing

**Comment by Avuidrauxs** [comment]
@atherdon , Final [PR](https://github.com/GroceriStar/graphql-server/pull/50) for GraphQL
