### ISSUE TITLE
move static data, related to ChickenKyiv project

### ISSUE THREAD

**Issue by atherdon** [GroceriStar/groceristar-fetch#2]
please check the current state of package.
right now it works for our search form
and i want to add static data for another project.
Previous code should work too.
more details here: https://github.com/GroceriStar/static-data/issues/10

**Comment by anupmahadev** [comment]
Hello Arthur,
I did not get the problem statement exactly. Could you please specify what  exactly I should do?

**Comment by atherdon** [comment]
@anupmahadev sure, not a problem.
First part: please review this package and explain me what do you think we're doing here. Then i'll add data related to a next steps

**Comment by anupmahadev** [comment]
Yes I got to know that the code is written for the various ingredients, as well as the recipes accordingly. I need to move the static data to the chickenKyiv project. I have written about what test case can be done. Please check in the comments of the next section.

**Comment by atherdon** [comment]
Second step: you should add another file-clone to index.js
at this file, we'll include other files, related only to ChickenKyiv (i want to keep both cases separately for now)
Third step: add tests

**Comment by atherdon** [comment]
@anupmahadev I want to push this task forward - can you tell me - do you have any questions?

**Comment by atherdon** [comment]
@vadim9999 can you start to work on this task, we need to pass that data to our other team member

**Comment by vadim9999** [comment]
@atherdon  I can't understand what should I do

**Comment by atherdon** [comment]
@vadim9999 basically it's the same kind of work that you've done before.
you should go to `static-data` repository, and at task#10 you will see list of files, that should be moved to our repository. like 3-4 files. then we should create methods for this files, and apply tests.
Literally the same kind of stuff that you did before

1) move files, related to ChickenKyiv into this repository
2) connect that files inside our plugin
3) create methods that will return data from that files
4) create tests for that methods
5) send pull request

**Comment by atherdon** [comment]
@vadim9999 did you add our methods to readme file? if not - please do

**Comment by atherdon** [comment]
@vadim9999 i think we can close this task, right?

**Comment by vadim9999** [comment]
@atherdon yes
