### ISSUE TITLE
[Groceristar][methods]

### ISSUE THREAD

**Issue by atherdon** [GroceriStar/groceristar-fetch#20]
- [x] create a separate file, that will include json files, related to groceristar project and creation of methods, that return that arrays.
- [x] connect this file to index.js and export our methods, so that can be called from outside.

**Comment by vadim9999** [comment]
@atherdon do you mean cut all methods from index.js and insert them in new file? After connect this file to index.js?

**Comment by atherdon** [comment]
yep


On 12-Jul-2018 at 07:17 PM, Vadim wrote:


@atherdon <https://github.com/atherdon> do you mean cut all methods from
index.js and insert them in new file? After connect this file to index.js?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/GroceriStar/groceristar-fetch/issues/20#issuecomment-404620274>,
or mute the thread
