### ISSUE TITLE
Intro to this project

### ISSUE THREAD

**Issue by atherdon** [GroceriStar/groceristar-fetch#229]
You need to read readme file: https://github.com/GroceriStar/groceristar-fetch/blob/master/README.md
it also contains links to articles, where I explaining some details. If something will be not clear - don't hesitate and ask questions.

Tasks, that you can take(feel free to ask clarification if something is not clear):
- https://github.com/GroceriStar/groceristar-fetch/issues/189
- https://github.com/GroceriStar/groceristar-fetch/issues/173

**Comment by Estherns** [comment]
Noted. Let me go through it

**Comment by atherdon** [comment]
additional simple task for you #231

**Comment by atherdon** [comment]
I added you to our organization, in order to accept invite, please follow this link: https://github.com/GroceriStar

**Comment by atherdon** [comment]
#231 is our most pending task right now, when you'll be able - please start from it

**Comment by Estherns** [comment]
Okay fine.

**Comment by atherdon** [comment]
awesome - thanks!
