### ISSUE TITLE
if we'll change our `get` methods to variables - our tests crashing.

### ISSUE THREAD

**Issue by atherdon** [GroceriStar/groceristar-fetch#246]
#245

**Comment by atherdon** [comment]
@wahaj-47 Ok, here we'll chat with you about our latest changes in #250 
you tell me this: https://github.com/GroceriStar/groceristar-fetch/pull/250#issuecomment-472531840

Can you give me more details about why you don't like this approach?
Then I'll explain my reasons and we'll find a consensus.

**Comment by atherdon** [comment]
https://github.com/GroceriStar/groceristar-fetch/issues/173#issuecomment-473013666

**Comment by wahaj-47** [comment]
> @wahaj-47 Ok, here we'll chat with you about our latest changes in #250
> you tell me this: [#250 (comment)](https://github.com/GroceriStar/groceristar-fetch/pull/250#issuecomment-472531840)
> 
> Can you give me more details about why you don't like this approach?
> Then I'll explain my reasons and we'll find a consensus.

We created a __get() method that did nothing except passing some argument to parser() method. We could have just used the parser() method in its place. Now we've got a __find() method which is also doing the same thing as __get() but with a few extra steps. So we can also use the __find() method in place of the __get() method.

**Comment by atherdon** [comment]
Ok, I understand. But why we have such complex structures like `__find(__get)`. Because I don't like them

**Comment by wahaj-47** [comment]
Yes exactly, why aren't we using the parser() method as it is.

**Comment by atherdon** [comment]
it's debatable. I mean right now - when we have a more clean code - it's
easy to think about changes.

**Comment by atherdon** [comment]
For some reasons I think we did this
