### ISSUE TITLE
search files tests

### ISSUE THREAD

**Issue by atherdon** [GroceriStar/groceristar-fetch#253]
1) rename staticFiles to files.test.js
2) add tests for each file that we connect in files.js

**Comment by atherdon** [comment]
@wahaj-47 can be one of your next tasks
I add you to our github organization, please visit https://github.com/GroceriStar in order to accept an invite

**Comment by wahaj-47** [comment]
There's a file sd-wrapper that I've not added a test for, it can't be done using the _find() method in search.js because we're not using sd-wrapper file in search.js

**Comment by atherdon** [comment]
maybe you got me wrong. 
right now we have one test, related to one file: https://github.com/GroceriStar/groceristar-fetch/blob/master/src/projects/Search/staticFiles.test.js#L4-L7
I just want more similar tests here

**Comment by wahaj-47** [comment]
This one complete right ?

**Comment by atherdon** [comment]
I'm not sure, because of your last comment, related to sd-wrapper. I didn't
get it

**Comment by wahaj-47** [comment]
We currently do not have a test for sd-wrapper because for testing the sd-wrapper because we can't test it using __find() method.

**Comment by wahaj-47** [comment]
Or maybe get the parsed version of sd-wrapper file.

**Comment by atherdon** [comment]
ok, I understand now

**Comment by wahaj-47** [comment]
So what do you think we should do ?

**Comment by wahaj-47** [comment]
> Or maybe get the parsed version of sd-wrapper file.

Okay, I found the sd-wrapper index file, Its not a data file so I think we need to create a new method specifically for testing this file

**Comment by atherdon** [comment]
first of all, `sd-wrapper` is a separated repository. So any code changes should be applied here: https://github.com/GroceriStar/sd

the second problem is - at `sd-wrapper` i'm trying to move into a new approach of building modules. Maybe you know part of my plan, from articles, that we have in `groceristar-fetch readme. So sd-wrapped is building with Babel and should be packed with Rollup. But right now we have some issues there. By issues i mean, my latest code changes cannot be published in npm, due to errors.  It's not about my own code(I assume). The biggest issue that we have is related to json files. Actually, ES6 didn't support JSON as type. Usually, people convert json files into js files, where you export an array. But I still want to have JSON files, because it makes the code more independent. So I install a few modules that should help us with ES6-json related issue, but it looks like that plugins are outdated. I create an issue, at their GitHub repositories, and still waiting.

Why I'm explaining this? You can go a fork `sd-wrapper`, code on it and i'll be able to review your code. 
Just be ready that our changes may not be published at npm for a few weeks.

**Comment by atherdon** [comment]
Ok, looks like maintainer of a plugin that we're using committing changes today. So maybe we'll be able to push my changes at sd-wrapper today

**Comment by atherdon** [comment]
Ok, module that we needed was upgraded and i'm pushing a new version of sd-wrapper here. Be ready that things can break here or tests will fail

**Comment by wahaj-47** [comment]
Where ever staticData object is used to retrieve the JSON file, we get undefined returned.

**Comment by atherdon** [comment]
give me a code line

**Comment by atherdon** [comment]
#268

**Comment by atherdon** [comment]
> Where ever staticData object is used to retrieve the JSON file, we get undefined returned.

@wahaj-47 I have doubts about this. I can be wrong(usually), but I have an assumption, that when you sync our last changes - you didn,t run `yarn install` locally. and it can be a case because when I publish a new version of `sd-wrapper` i upgrade module at `fetch` as well. Please check this and confirm, if an error is still there

**Comment by atherdon** [comment]
i think we can close this task, right?

**Comment by wahaj-47** [comment]
Yeah
