### ISSUE TITLE
export raw files from each project

### ISSUE THREAD

**Issue by atherdon** [GroceriStar/groceristar-fetch#254]
similar that you did in search.js
@wahaj-47

**Comment by wahaj-47** [comment]
Can you elaborate ?

**Comment by atherdon** [comment]
Sure: https://github.com/GroceriStar/groceristar-fetch/blob/master/src/projects/Search/search.js#L22-L27
https://github.com/GroceriStar/groceristar-fetch/blob/master/src/projects/Search/search.js#L184

**Comment by wahaj-47** [comment]
I think we should move this __find() method to helper.js and get rid of __get() method

**Comment by atherdon** [comment]
let's move `__find()` method, but keep `__get()` method as well. If our changes wouldn't broke the logic of project, dependable of this module - we'll think about it. Feel free to create a new issue at this repo, and explain where we need to remove `__get()` and how. So I'll be able to use that issue later and assign it to other interns

**Comment by wahaj-47** [comment]
I updated the test files, but now everything is broken. There is a new staticData object inside files.js of every project, I am guessing its got issues as well.

**Comment by atherdon** [comment]
Sure, let's solve it together. Open your PR with changes
