### ISSUE TITLE
replace similar tests with functions

### ISSUE THREAD

**Issue by atherdon** [GroceriStar/groceristar-fetch#257]
0) change staticFiles.test at all of our projects. See `search` folder for example
1) all of our files.test.js have similar logic: we check if files exist/methods return some data. It can be simplified.
2) Compare `GraphQL/files.test.js` with other similar files and you'll get a difference

it's a very simple task. you just need to be focused and don't have mistakes. But if you'll have mistakes - we'll see them :)

**Comment by atherdon** [comment]
@tihaami

**Comment by tihaami** [comment]
its src/projects/graphQL/graphQL.test.js , not GraphQL/files.test.js right  ? Cuz i aint got any file with that name..

**Comment by atherdon** [comment]
because you didn't finished first point of this task :)

**Comment by tihaami** [comment]
Ahh.. Sorry, i'm a bit confused, I thought point 1 and 2 were mentioned
there as an example. And i had to take hints from point 1 and 2 in order to
complete point 0 ?

**Comment by tihaami** [comment]
Alright i get it now..
