### ISSUE TITLE
making fetch test coverage working

### ISSUE THREAD

**Issue by atherdon** [GroceriStar/groceristar-fetch#268]
@wahaj-47 Ok, merged your changes. Let's find out step by step what should be done, in order to fix test coverage.
First of all - I updated sd-wrapper. You can take a look how files are exported from it here: https://github.com/GroceriStar/sd/blob/master/src/index.js
and how connected here: https://github.com/GroceriStar/groceristar-fetch/blob/master/src/projects/Search/files.js

**Comment by wahaj-47** [comment]
Here if I console.log mealCalendar I get undefined, but for firstVeganGLMC I get the JSON
```
const mealCalendar = staticData.mealCalendar

const firstVeganGLMC =
  require('@groceristar/sd-wrapper/dist/data/MealCalendar/First-Vegan-Grocery-List-MC.json')
```

**Comment by atherdon** [comment]
Ok, then my assumption is right: https://github.com/GroceriStar/groceristar-fetch/issues/253#issuecomment-474988989
Because in the latest version of `sd-wrapper` - we don't have raw files, stored at `dist/data` - reason: second plugin at rollup crashed as well :)

**Comment by wahaj-47** [comment]
Yes you were right.

**Comment by atherdon** [comment]
But we still have problems. And I think you able to cover it yourself :) if you want - you can tell me your plan what you need to do and i'll confirm it

**Comment by atherdon** [comment]
Just another way to check how tests running is to use Travis CI job log - https://travis-ci.org/GroceriStar/groceristar-fetch
as tests errors long - it's the easiest way to scroll it

**Comment by wahaj-47** [comment]
> But we still have problems. And I think you able to cover it yourself :) if you want - you can tell me your plan what you need to do and i'll confirm it

I plan to just use staticData object everywhere.

**Comment by wahaj-47** [comment]
> > But we still have problems. And I think you able to cover it yourself :) if you want - you can tell me your plan what you need to do and i'll confirm it
> 
> I plan to just use staticData object everywhere.

This won't work, because some JSONs are not being imported at sd-wrapper.

**Comment by atherdon** [comment]
> I plan to just use staticData object everywhere.
Great

> This won't work, because some JSONs are not being imported at sd-wrapper.
Then what you should do?

**Comment by wahaj-47** [comment]
If the sd-wrapper is fixed to return all the required JSONs then I can use staticData object.The tests run fine for the  JSONs that are being returned correctly.

**Comment by atherdon** [comment]
you just need to finish what i didn't finish. apply changes at sd-wrapper

**Comment by atherdon** [comment]
Ok, I install the latest version to groceristar-fetch. you can work on it

**Comment by atherdon** [comment]
sd-wrapper updated

**Comment by atherdon** [comment]
ok, looks like it improve test coverage. But we still have issues. Details: https://travis-ci.org/GroceriStar/groceristar-fetch

**Comment by atherdon** [comment]
https://github.com/GroceriStar/sd/pull/48

**Comment by atherdon** [comment]
i install your latest changes

**Comment by atherdon** [comment]
sd-wrapper updated, tell me if you'll need something else from me

**Comment by atherdon** [comment]
btw, did we finish this task of we still have some errors, related to import json files?

**Comment by wahaj-47** [comment]
Showcase and unitconvertion don't have any tests

**Comment by atherdon** [comment]
you right. showcase don't have tests because it's not necessary now. actually showcase is a part of GS. i just make it as separated branch in order to make it less complex. Showcase is just a place - where we display grocery lists. so it only getting and displaying data that we have.

UnitConvertion is an important and big topic, but right now i'm not ready to start it. When we'll finish some of our current pending tasks, then pack it well, in order to present our library to public. Then we'll create a website and submit website+package to ProductHunt. And only if we'll receive an attention - we'll be able to jump into this part of package.

**Comment by atherdon** [comment]
closing this task. will think later about what we can do next
