### ISSUE TITLE
[Groceristar][remove static data from import script]

### ISSUE THREAD

**Issue by atherdon** [GroceriStar/groceristar-fetch#28]
https://github.com/GroceriStar/groceristar/tree/master/bin/old-delete-later/grocery
I think this not a complex thing, but tell me if you'll have questions.

**Comment by atherdon** [comment]
another video: https://www.useloom.com/share/870465b5314e418d80aa9ae9143fa564

**Comment by vadim9999** [comment]
@atherdon https://github.com/GroceriStar/groceristar/pull/558

**Comment by atherdon** [comment]
thank you!
