### ISSUE TITLE
Incorrect syntax in helper.js causing all tests to fail

### ISSUE THREAD

**Issue by azaidi4** [GroceriStar/groceristar-fetch#318]
https://github.com/GroceriStar/groceristar-fetch/blob/2163e6aea7e8fedea48909ba75921622cfed193f/src/helper.js#L32-L42

**Comment by atherdon** [comment]
as you find this thing - maybe it's a good next task for you...
Problem that I see - we have a lot of methods between different projects, that actually doing a same thing.
We're grab static arrays from files and then re-arrange a data, so it can work in our different projects.
It's a big thing. So let's split it into a small chunks.
you saw 2 blank methods that i created. The main goal of these methods - reduce lines of our code later, without crashing it.

method that generate an id - will return result from uuid
method that generate date - will return result from dayjs. 

tell me if you get my idea or i should give you more details

**Comment by atherdon** [comment]
We can start from #313 `GraphQL` section - because i'll be able to check your changes quickly at our server.

**Comment by azaidi4** [comment]
I've submitted a pull request for `GraphQL` section in #313. Closing this thread as the issue is resolved.
