### ISSUE TITLE
import objects in files.js that is located in src/projects/UnitConvertion

### ISSUE THREAD

**Issue by vadim9999** [GroceriStar/groceristar-fetch#360]
import and export objects (measurementSystem and MeasurementUnits) in files.js from sd-wrapper. Import and export from sd-wrapper you can seen in https://github.com/GroceriStar/groceristar-fetch/blob/master/src/projects/GroceriStar/files.js
files.js is located in src/projects/UnitConvertion. 
After it add tests in files.test.js that objects are not empty.

**Comment by vadim9999** [comment]
@Beni03

**Comment by Beni03** [comment]
Ok. Will work on it.

**Comment by Beni03** [comment]
I could not find those objects(measurementSystems and measurementUnits) from sd-wrapper module

**Comment by vadim9999** [comment]
Sorry, I will update package sd-wrapper

**Comment by Beni03** [comment]
Ok

**Comment by vadim9999** [comment]
@Beni03 I have updated sd-wrapper. Try again

**Comment by Beni03** [comment]
Its working now. update files.js

**Comment by atherdon** [comment]
i think it's related to #370
