### ISSUE TITLE
create test for getKeyArrayDepAndIng

### ISSUE THREAD

**Issue by vadim9999** [GroceriStar/groceristar-fetch#364]
In src/projects/GroceriStar/groceristar.js you will find getKeyArrayDepAndIng(). Write tests for it. What tests we should be created for this function?

**Comment by vadim9999** [comment]
@Beni03 This task is for you. I don't know why I can't add you to assignees. I have doesn't publish new version of sd, because we have there some troubles with import I think other interns will quick fix it

**Comment by Beni03** [comment]
> In src/projects/GroceriStar/groceristar.js you will find getKeyArrayDepAndIng(). Write tests for it. What tests we should be created for this function?

Trying to understand the code. Will work on it.

**Comment by Beni03** [comment]
> @Beni03 This task is for you. I don't know why I can't add you to assignees. I have doesn't publish new version of sd, because we have there some troubles with import I think other interns will quick fix it

OK. Will check why I cannot get assigned.

**Comment by atherdon** [comment]
is this task finished?

**Comment by vadim9999** [comment]
No

**Comment by Beni03** [comment]
Not yet. Will work on it.

**Comment by Beni03** [comment]
@vadim9999 
We need to test if objects(departments and ingredients) are not empty

**Comment by atherdon** [comment]
can you do it?

>

**Comment by Beni03** [comment]
Yes. I ll do it

**Comment by Beni03** [comment]
If I am right, tests to check objects are not empty has to be written in main test file. So, I have created a new test file for getKeyArrayDepAndind() and added some tests particularly for it.

**Comment by atherdon** [comment]
#408 
looks fine. not running it locally, but i think it what we needed. @Beni03 do you think we can close this task, right?

**Comment by Beni03** [comment]
Yes

**Comment by atherdon** [comment]
awesome! do you have a next task todo? because I have a task description for you, but it's blocked right now - we need to wait for changes from our sd-wrapper repository

**Comment by Beni03** [comment]
No, right now I do not have any task assigned. Ok will wait for the next
task.

**Comment by atherdon** [comment]
got your message.

**Comment by atherdon** [comment]
you can grab this task for now: https://github.com/GroceriStar/sd/issues/362

**Comment by Beni03** [comment]
👍
