### ISSUE TITLE
display data related UnitConversion in play.js

### ISSUE THREAD

**Issue by vadim9999** [GroceriStar/groceristar-fetch#373]
1. Add to Import and export generatedMeasurementUnits and generatedMeasurementSystem. 
2. Create file play.js in projects/UnitConversion. Import and display in console log all variables that are in files.js that in UnitConversion.
3. Add tests that check if variable is not empty, is it array.

**Comment by vadim9999** [comment]
@Beni03

**Comment by atherdon** [comment]
i think we need to extend details for this task

**Comment by atherdon** [comment]
@vadim9999 
1. Does `generatedMeasurementUnits` and `generatedMeasurementSystem` are the actual names of our files? 
At which `project` it should be imported?
What methods should we create - what will they do?
Can you provide some examples of methods that looks similar, in order to help?

2. maybe you can point play.js from another `project` that can be used as example as well?
Can you explain, how to run a script, that will call our new play.js file?

3. Can you explain where tests need to be saved(place)?
Can you provide some tests as an example of what we're trying to archive?

**Comment by vadim9999** [comment]
1. generatedMeasurementUnits and generatedMeasurementSystem  are generated files based on MeasurementUnits and MeasurementSystem. Which project and other details I don't know.I thought you know. Because if this files was added that they someone need
2. example of play.js from GroceriStar https://github.com/GroceriStar/groceristar-fetch/blob/master/src/projects/GroceriStar/play.js. 
To call it, need to add in package.json in block scrips.
3. tests we can save in new created folder tests in UnitConvertion. Example of tests https://github.com/GroceriStar/groceristar-fetch/blob/master/src/projects/GroceriStar/test/groceristar.test.js

**Comment by atherdon** [comment]
1. Does generatedMeasurementUnits and generatedMeasurementSystem are the actual names of our files?
I mean if we use them - we will receive a data from sd, right?

---
> Which project and other details I don't know.
As we creating play.js at `UnitConvertions` folder - then our methods should be located there too.

2. To call it, need to add in package.json in block scrips
can you be more specific? maybe we have an example at Readme?
@vadim9999

**Comment by Beni03** [comment]
where can I fine generatedMeasurementUnits and generatedMeasurementSystem?

**Comment by atherdon** [comment]
here you can see both versions(plain and generated as we need it)
https://github.com/GroceriStar/sd/blob/master/src/files.js#L44-L47

try just to replace variable names and i think it's done(if it wouldn't generate an error)

**Comment by atherdon** [comment]
as i think this change will be very easy for you, please feel free and grab this next task: https://github.com/GroceriStar/sd/issues/299

**Comment by Beni03** [comment]
Ok

**Comment by Beni03** [comment]
for this code,
![image](https://user-images.githubusercontent.com/16260275/57660129-e392b700-7599-11e9-958b-06b102f0235a.png)

output is,
![image](https://user-images.githubusercontent.com/16260275/57660179-1ccb2700-759a-11e9-9f3e-caf6dbc04833.png)


or, for this code,
![image](https://user-images.githubusercontent.com/16260275/57660212-556b0080-759a-11e9-99f2-31f35264c7b5.png)

the output is,
![image](https://user-images.githubusercontent.com/16260275/57660262-94995180-759a-11e9-9168-cd0ca0cb08ae.png)

**Comment by Beni03** [comment]
expecting me to use JSON.stringify(object) to display objects?

**Comment by atherdon** [comment]
you did it right. now i see how do you call the script. But, we have a
better way for it.
Please check this lines and update it -
https://github.com/GroceriStar/groceristar-fetch/blob/master/package.json#L8-L11
then i'll be able to merge your pull request

>

**Comment by atherdon** [comment]
closing
