### ISSUE TITLE
master of readme

### ISSUE THREAD

**Issue by atherdon** [GroceriStar/groceristar-fetch#393]
**Is your feature request related to a problem? Please describe.**

add https://github.com/GroceriStar/groceristar-fetch/issues/373#issuecomment-490644575 too.

**Is it was created as task at GitHub issues? Please provide an issue number or link**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by atherdon** [comment]
right now i have feeling that readme here is more for me. so i think we need to extend it and make better. 
Similar to what you did at sd repository and convert it from temporary code repo to a cool looking bad-ass shit.

**Comment by hirdbluebird** [comment]
https://gph.is/28QBLPQ

**Comment by atherdon** [comment]
hmm, looks like you also don't know about Markdown as well.

![xxx](https://media.giphy.com/media/7JjpxuFrfvOtr8VOSQ/giphy.gif)

>

**Comment by atherdon** [comment]
eeemm. not work from email :(

**Comment by hirdbluebird** [comment]
@atherdon put the label `in progress` here

**Comment by atherdon** [comment]
closing
