### ISSUE TITLE
move readme from

### ISSUE THREAD

**Issue by atherdon** [GroceriStar/groceristar-fetch#5]
- [x] checkout https://github.com/GroceriStar/static-data into your PC
- [x] move readme content into this project(but keep the data that we have here) read this readme and update parts that you think is necessary. If this is not clear - you can ask me here.
- [ ] remove readme from static-data project
- [ ] commit+push static-data updates and this commit+push updates to this repository
@MinkoJ2

**Comment by atherdon** [comment]
please follow this link: https://github.com/GroceriStar/groceristar-fetch/invitations

**Comment by atherdon** [comment]
based on @MinkoJ2 comments: 
>> Maybe I cannot make commits to this repository. When i read the task, i removed few lines and click "commit button"

a) you can make commits - because i add you to this repo as contributor
b) maybe you forgot to click "push". What client are you using for GIT?

**Comment by MinkoJ2** [comment]
Я не могу ничего [тут](https://github.com/GroceriStar/static-data) коммитить
@atherdon

**Comment by atherdon** [comment]
@MinkoJ2 can you show me your code changes at your forked version?

**Comment by atherdon** [comment]
on pause right now. learning git/github basics

**Comment by atherdon** [comment]
@MinkoJ2  tell me when you'll watch some git related videos and be ready to continue with this task

**Comment by MinkoJ2** [comment]
Error - `permission to GroceriStar/static-data.git denied to MinkoJ2.`
@atherdon

**Comment by atherdon** [comment]
create a fork from that repo


On 15-Jul-2018 at 12:16 PM, Edward wrote:


Error - permission to GroceriStar/static-data.git denied to MinkoJ2.
@atherdon <https://github.com/atherdon>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/GroceriStar/groceristar-fetch/issues/5#issuecomment-405088084>,
or mute the thread

**Comment by MinkoJ2** [comment]
**[Check](https://github.com/MinkoJ2/static-data)**

**Comment by atherdon** [comment]
No, you got me wrong. but this is good for practice your git skills.

I wanted to move Readme content **from** static-data repository, **into** groceristar-fetch.
`static data` was created in purpose to keep all data in one place, but `groceristar-fetch` is a repository with really working module, that we're using in our development process

**Comment by MinkoJ2** [comment]
I do not understand. In which file

**Comment by atherdon** [comment]
@MinkoJ2 please review the latest version of readme file from groceristar-fetch.
Vadim made some changes and it started to look differently - can you take a look, and fix that small things?

Btw, don't forget that this task have some unfinished work(sub-tasks in task description)

**Comment by atherdon** [comment]
I create a video for you, please check it here: https://www.useloom.com/share/44f6a90b64c64e43a75dc027d06852bf

**Comment by atherdon** [comment]
I didn't see that latest 2 options is completed. Should i review other things?

**Comment by atherdon** [comment]
didn't see any pull requests with your changes here: https://github.com/GroceriStar/static-data

**Comment by atherdon** [comment]
and i didn't see a lot of changes at groceristar-fetch readme. looks like you trying to do it fast. So we'll should go slow from now.

**Comment by MinkoJ2** [comment]
**I do not understand what to do, I made the README in both sections
[1](https://github.com/GroceriStar/groceristar-fetch)
[2](https://github.com/MinkoJ2/static-data)**

**Comment by MinkoJ2** [comment]
@atherdon

**Comment by atherdon** [comment]
so it was 3 days ago, not today.
on pause right now, don't want to explain it

**Comment by atherdon** [comment]
it's not done. if you want to understand why - then try to ask a right questions. It's not good to hear - i don't know what to do. Please be more focused.

**Comment by atherdon** [comment]
- [ ] there a new issues in Readme, please take a look and fix the formatting errors
