### ISSUE TITLE
create pretty code images for my upcoming article

### ISSUE THREAD

**Issue by atherdon** [GroceriStar/groceristar-fetch#96]
you'll be able to learn it a bit, also i'll be able to share this article with other team members.
note, code should be clear and separated from comments or other dirt that we have
and it should work as a separated entity
- [x]  https://github.com/GroceriStar/groceristar-fetch/blob/master/groceristar.test.js#L8-L9
- [x] https://github.com/GroceriStar/groceristar-fetch/blob/master/groceristar.test.js#L14-L18 (please add test wrapper)
- [x]  https://github.com/GroceriStar/groceristar-fetch/blob/master/groceristar.test.js#L20-L24 (add test wrapper)
- [x]  https://github.com/GroceriStar/groceristar-fetch/blob/master/groceristar.test.js#L26-L31
- [x] https://github.com/GroceriStar/groceristar-fetch/blob/master/groceristar.test.js#L33
- [x] https://github.com/GroceriStar/groceristar-fetch/blob/master/groceristar.test.js#L51-L57
- [x] https://github.com/GroceriStar/groceristar-fetch/blob/master/groceristar.test.js#L59-L65
https://github.com/GroceriStar/groceristar-fetch/blob/master/groceristar.test.js#L67-L69
https://github.com/GroceriStar/groceristar-fetch/blob/master/groceristar.test.js#L87-L105 (only uncommented part)
https://github.com/GroceriStar/groceristar-fetch/blob/master/groceristar.test.js#L90-L92(with test part)

**Comment by vadim9999** [comment]
![carbon 1](https://user-images.githubusercontent.com/35640573/46545379-e3795d00-c8ce-11e8-82c6-ce7c81351051.png)
@atherdon Should I change tested data on data from groceristar? The style of image is good?

**Comment by atherdon** [comment]
styles are good! 
for some samples, we need to use samples, related to GS

**Comment by vadim9999** [comment]
![1](https://user-images.githubusercontent.com/35640573/46569949-7ebd1180-c965-11e8-8c13-b437a8ab11e0.png)
![2](https://user-images.githubusercontent.com/35640573/46569950-7ebd1180-c965-11e8-8f9a-a4e67c1a7b8f.png)
![3](https://user-images.githubusercontent.com/35640573/46569951-7ebd1180-c965-11e8-8305-60f0f6661feb.png)
![4](https://user-images.githubusercontent.com/35640573/46569952-7ebd1180-c965-11e8-8c02-3738c5e0e6a0.png)
![5](https://user-images.githubusercontent.com/35640573/46569953-7f55a800-c965-11e8-9087-a275cfe47bcf.png)
![6](https://user-images.githubusercontent.com/35640573/46569955-7f55a800-c965-11e8-944a-f06502e3493d.png)
![7](https://user-images.githubusercontent.com/35640573/46569956-7f55a800-c965-11e8-87a8-e63fdf28e0c5.png)
![8](https://user-images.githubusercontent.com/35640573/46569957-7f55a800-c965-11e8-8c0b-08388dc58490.png)
![9](https://user-images.githubusercontent.com/35640573/46569958-7f55a800-c965-11e8-90de-95c41898d7f2.png)
![Uploading 10.png…]()
![Uploading 11.png…]()

**Comment by atherdon** [comment]
@vadim9999 last two was not uploaded
anything else looks amazing

**Comment by vadim9999** [comment]
![11](https://user-images.githubusercontent.com/35640573/46580016-f00fc980-ca24-11e8-9511-5f4d8cc8781f.png)
![10](https://user-images.githubusercontent.com/35640573/46580017-f00fc980-ca24-11e8-86d9-c0c5f88a2e82.png)

**Comment by atherdon** [comment]
big thank you
